name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: false

      - name: Restore
        run: dotnet restore ./SiteMonitor.csproj

      - name: Build
        run: dotnet build ./SiteMonitor.csproj -c Release --no-restore

      - name: Test
        run: echo "no tests"

      - name: Publish
        run: dotnet publish ./SiteMonitor.csproj -c Release -o out --no-restore
